/** @format */

import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './css/globals.css';

const poppins = Poppins({ weight: ['300', '400', '500', '500', '700', '800', '900'], subsets: ['latin'] });

export const metadata: Metadata = {
   title: 'Youthnews',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang='en'>
         <body className={poppins.className}>{children}</body>
      </html>
   );
}
